In [ ]:
import matplotlib.pyplot as plt
import os
import re
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc, roc_auc_score, matthews_corrcoef
from imblearn.combine import SMOTEENN
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from imblearn.over_sampling import RandomOverSampler
from xgboost import XGBClassifier
from sklearn.preprocessing import OneHotEncoder

In [ ]:
umap = pd.read_csv('/content/F_ptmint_prot_umap.csv')
tsne = pd.read_csv('/content/F_ptmint_prot_tsne.csv')
pca = pd.read_csv('/content/F_ptmint_prot_pca.csv')
eliminated = pd.read_csv('/content/F_ptmint_prot_wind_enc.csv')

In [ ]:
features = ['prot_2_882',
'prot_2_847',
'prot_2_957',
'prot_2_1005',
'prot_2_172',
'prot_2_434',
'prot_2_592',
'prot_1_173',
'prot_2_59',
'prot_1_340',
'prot_1_352',
'prot_2_1013',
'prot_2_583',
'prot_1_56',
'prot_2_483',
'prot_2_861',
'wind_882',
'prot_1_829',
'wind_792',
'prot_1_561',
'prot_1_291',
'prot_1_815',
'prot_2_951',
'prot_2_114',
'prot_2_901',
'prot_2_107',
'wind_596',
'wind_532',
'prot_2_44',
'prot_1_374',
'prot_2_372',
'prot_2_471',
'prot_2_319',
'wind_564',
'prot_2_996',
'wind_961',
'wind_613',
'prot_2_573',
'wind_978',
'prot_2_193',
'prot_1_651',
'prot_1_547',
'prot_1_501',
'prot_2_803',
'wind_495',
'wind_55',
'wind_659',
'prot_1_466',
'prot_2_6',
'wind_420',
'wind_836',
'wind_865',
'wind_703',
'wind_850',
'wind_922',
'prot_1_453',
'wind_878',
'prot_2_876',
'prot_1_887',
'wind_580',
'wind_793',
'prot_1_253',
'prot_2_249',
'prot_2_739',
'prot_1_338',
'wind_393',
'wind_550',
'wind_778',
'wind_220',
'prot_1_895',
'prot_2_810',
'prot_1_559',
'Is_int',
'PTM']

print(len(features))

74


In [ ]:
umap_x = umap.drop(columns = ['Effect', 'Unnamed: 0', 'Site'])
umap_y = umap['Effect']


tsne_x = tsne.drop(columns = ['Effect', 'Unnamed: 0', 'Site'])
tsne_y = tsne['Effect']

pca_x = pca.drop(columns = ['Effect', 'Unnamed: 0', 'Site', 'protbert', 'int_protbert'])
pca_y = pca['Effect']

eliminated_x = eliminated.drop(columns = ['Effect', 'Unnamed: 0','Site'])
eliminated_y = eliminated['Effect']

print(pca_x.head())


   PTM  Is_int  prot_1_0  prot_1_1  prot_1_2  prot_1_3  prot_1_4  prot_1_5  \
0    3       0 -7.971703 -0.417247  2.350504 -3.315564 -5.896609  9.490856   
1    3       0  7.422797 -3.919816 -8.453760  5.990222  4.319603  2.118616   
2    3       1 -2.208193 -5.230134 -3.938176 -1.542876  7.678240  4.189340   
3    3       1 -2.208193 -5.230134 -3.938176 -1.542876  7.678240  4.189340   
4    3       0 -3.758822 -3.139899 -4.889634  2.103601  1.822569 -4.790252   

   prot_1_6  prot_1_7  ...  wind_prot_190  wind_prot_191  wind_prot_192  \
0 -3.916715  0.218848  ...      -0.958381       0.045456      -1.464553   
1  5.744848  0.765174  ...      -0.275604      -0.577459      -0.603420   
2  4.559882  5.064302  ...      -0.725204      -0.218523       0.712108   
3  4.559882  5.064302  ...      -0.724598      -0.218572       0.712170   
4  5.763516  1.306211  ...       0.147346       0.161696       0.133738   

   wind_prot_193  wind_prot_194  wind_prot_195  wind_prot_196  wind_prot_197  \


In [ ]:
UX_train, UX_test, Uy_train, Uy_test = train_test_split(umap_x,umap_y, test_size=0.1, random_state=42)
TX_train, TX_test, Ty_train, Ty_test = train_test_split(tsne_x,tsne_y, test_size=0.1, random_state=42)
PX_train, PX_test, Py_train, Py_test = train_test_split(pca_x,pca_y, test_size=0.1, random_state=42)
EX_train, EX_test, Ey_train, Ey_test = train_test_split(eliminated_x, eliminated_y, test_size=0.1, random_state=42)


In [ ]:
rf = RandomForestClassifier(random_state = 10)
rf_obc = rf.fit(UX_train, Uy_train)
y_pred= rf_obc.predict(UX_test)
y_prob = rf_obc.predict_proba(UX_test)

print(classification_report(Uy_test, y_pred))
print(confusion_matrix(Uy_test, y_pred))
#print(roc_auc_score(y_test_o, y_prob[:,1]))
print(matthews_corrcoef(Uy_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.92      0.88       228
           1       0.81      0.67      0.74       122
           2       1.00      1.00      1.00         2

    accuracy                           0.83       352
   macro avg       0.88      0.86      0.87       352
weighted avg       0.83      0.83      0.83       352

[[209  19   0]
 [ 40  82   0]
 [  0   0   2]]
0.626856108094796


In [ ]:
rf = RandomForestClassifier(random_state = 10)
rf_obc = rf.fit(PX_train, Py_train)
y_pred= rf_obc.predict(PX_test)
y_prob = rf_obc.predict_proba(PX_test)

print(classification_report(Py_test, y_pred))
print(confusion_matrix(Py_test, y_pred))
#print(roc_auc_score(y_test_o, y_prob[:,1]))
print(matthews_corrcoef(Py_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.97      0.89       228
           1       0.93      0.61      0.74       122
           2       1.00      1.00      1.00         2

    accuracy                           0.85       352
   macro avg       0.92      0.86      0.88       352
weighted avg       0.86      0.85      0.84       352

[[222   6   0]
 [ 47  75   0]
 [  0   0   2]]
0.6718968084779012


In [ ]:
rf = RandomForestClassifier(random_state = 10)
rf_obc = rf.fit(TX_train, Ty_train)
y_pred= rf_obc.predict(TX_test)
y_prob = rf_obc.predict_proba(TX_test)

print(classification_report(Ty_test, y_pred))
print(confusion_matrix(Ty_test, y_pred))
#print(roc_auc_score(y_test_o, y_prob[:,1]))
print(matthews_corrcoef(Ty_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.93      0.86       228
           1       0.80      0.57      0.66       122
           2       1.00      1.00      1.00         2

    accuracy                           0.80       352
   macro avg       0.87      0.83      0.84       352
weighted avg       0.80      0.80      0.79       352

[[211  17   0]
 [ 53  69   0]
 [  0   0   2]]
0.5530725367916978


In [ ]:
rf = RandomForestClassifier(random_state = 10)
rf_obc = rf.fit(EX_train, Ey_train)
y_pred= rf_obc.predict(EX_test)
y_prob = rf_obc.predict_proba(EX_test)

print(classification_report(Ey_test, y_pred))
print(confusion_matrix(Ey_test, y_pred))
#print(roc_auc_score(y_test_o, y_prob[:,1]))
print(matthews_corrcoef(Ey_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.96      0.88       228
           1       0.88      0.61      0.72       122
           2       1.00      1.00      1.00         2

    accuracy                           0.84       352
   macro avg       0.90      0.86      0.87       352
weighted avg       0.84      0.84      0.83       352

[[218  10   0]
 [ 47  75   0]
 [  0   0   2]]
0.6420468779727345


In [ ]:
rf = RandomForestClassifier()